Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 1.py
======================================================================
QUESTION 1: BANKING CHATBOT QUERY PARSER
======================================================================

[Input Query]: 'Show me the transactions with the card from last month'

--- PARSE TREES GENERATED BY CFG/PCFG ---

Parse Tree #1: High-Probability Parse (Transactions executed last month)
  Structure   : [VP [VP Show me [NP transactions]] [PP with the card] [PP from last month]]
  Semantics   : Fetch transactions made using the card where transaction_date = last_month.
  PCFG Weight : 0.65

Parse Tree #2: Low-Probability Parse (Card issued/created last month)
  Structure   : [VP Show me [NP transactions [PP with [NP the card [PP from last month]]]]]
  Semantics   : Fetch transactions for a specific card that was acquired last month.
  PCFG Weight : 0.2

--- PCFG AMBIGUITY RESOLUTION VERDICT ---
Selected Parse: High-Probability Parse (Transactions executed last month)
Reasoning     : Higher PCFG weight (0.65) prioritizes transaction-level temporal filtering.

--- FEATURE STRUCTURE AGREEMENT CHECK ---
Valid Pair   ('The customer' + 'checks') -> Unified FS: None
Invalid Pair ('The customers' + 'checks') -> Unified FS: None (Agreement Error Blocked)
>>> 
================== RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 2.py =================
Traceback (most recent call last):
  File "C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 2.py", line 174, in <module>
    run_demo_q1()
NameError: name 'run_demo_q1' is not defined. Did you mean: 'run_demo_q2'?

================== RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 2.py =================
Do you want to enter a custom voice command?
Enter 'y' for interactive mode or press Enter to run hardcoded demo: y

Enter voice command (e.g., 'Book a flight to Delhi with a window seat'): book a bus to chennai with a non window seat
======================================================================
QUESTION 2: VOICE ASSISTANT PARSING OPTIMIZATION
======================================================================

[Voice Input Stream]: 'book a bus to chennai with a non window seat'

--- 1. TOP-DOWN PARSER SIMULATION ---
Status               : Failed
Backtracking Cost    : 6 state comparisons
Limitation           : Fails on partial audio streams; causes latency spikes.

--- 2. EARLEY PARSER INCREMENTAL CHART SIMULATION ---
Stream Audio Buffer  : book a bus to ... [User still speaking]
Earley Chart States  : 0 parallel parsed states active
Partial Parse Status : Successful (Predictive state active before audio stream finishes)

--- 3. FULL STREAM PARSE RESULT ---
Tokens Processed     : 10 token positions charted.
Earley Advantage     : Dynamic programming chart memoizes paths, eliminating redundant backtracking entirely.

================== RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 3.py =================
Traceback (most recent call last):
  File "C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 3.py", line 153, in <module>
    run_demo_q1()
NameError: name 'run_demo_q1' is not defined. Did you mean: 'run_demo_q3'?

================== RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 3.py =================
Do you want to enter a custom medical report sentence?
Enter 'y' for interactive mode or press Enter to run hardcoded demo: 
======================================================================
QUESTION 3: HEALTHCARE NLP CLINICAL EXTRACTION ENGINE
======================================================================

[Raw Patient Report Sentence]:
"The doctor who reviewed the patient last week recommends starting medication and scheduling a follow-up visit in Chennai."

--- EXTRACTED STRUCTURED CLINICAL OUTPUT (JSON) ---
{
  "clinical_record": {
    "source_text": "The doctor who reviewed the patient last week recommends starting medication and scheduling a follow-up visit in Chennai.",
    "practitioner": {
      "role": "Doctor",
      "qualifier_clause": {
        "action": "reviewed",
        "target": "patient",
        "time_frame": "last week"
      }
    },
    "primary_recommendation": {
      "action_verb": "recommends",
      "clinical_actions": [
        {
          "type": "Treatment_Start",
          "intervention": "medication"
        },
        {
          "type": "Appointment_Scheduling",
          "event": "follow-up visit",
          "location": "Chennai"
        }
      ]
    },
    "validation_metadata": {
      "subject_verb_agreement": "Passed (3rd Person Singular)",
      "subcategorization_frames": "Verified Valid"
    }
  }
}

================== RESTART: C:\Users\cravi\OneDrive\Desktop\Jabastian college\NLP folder\NLP CO4 AT2\program 3.py =================
Do you want to enter a custom medical report sentence?
Enter 'y' for interactive mode or press Enter to run hardcoded demo: y

Enter medical sentence: i have a hand pain
======================================================================
QUESTION 3: HEALTHCARE NLP CLINICAL EXTRACTION ENGINE
======================================================================

[Raw Patient Report Sentence]:
"i have a hand pain"

--- EXTRACTED STRUCTURED CLINICAL OUTPUT (JSON) ---
{
  "clinical_record": {
    "source_text": "i have a hand pain",
    "practitioner": {
      "role": "Doctor",
      "qualifier_clause": {
        "action": "reviewed",
        "target": "patient",
        "time_frame": "last week"
      }
    },
    "primary_recommendation": {
      "action_verb": "recommends",
      "clinical_actions": [
        {
          "type": "Treatment_Start",
          "intervention": "medication"
        },
        {
          "type": "Appointment_Scheduling",
          "event": "follow-up visit",
          "location": "Chennai"
        }
      ]
    },
    "validation_metadata": {
      "subject_verb_agreement": "Passed (3rd Person Singular)",
      "subcategorization_frames": "Verified Valid"
    }
  }
}
