from typing import Dict, List, Tuple, Any, Optional
import math


class BankingQueryParser:
    """
    Simulates CFG ambiguity analysis, feature structure unification,
    and PCFG probability evaluation for banking queries.
    """

    def __init__(self) -> None:
        # PCFG Rules for Prepositional Phrase (PP) Attachment
        # Rule set A: PP attaches to Noun (Card from last month)
        # Rule set B: PP attaches to Verb Phrase / Direct Object (Transactions from last month)
        self.pcfg_rules: Dict[str, float] = {
            "VP -> VP PP_card PP_time": 0.65,  # High prob: Time applies to transactions
            "NP -> NP PP_time": 0.20,           # Lower prob: Time applies to card directly
            "PP_card -> Prep_with NP_card": 0.80,
            "PP_time -> Prep_from NP_time": 0.85,
        }

    def analyze_ambiguity(self, query: str) -> Dict[str, Any]:
        """
        Analyzes prepositional phrase attachment ambiguity in the query.
        """
        if not query or not isinstance(query, str):
            raise ValueError("Input query must be a non-empty string.")

        tokens = query.strip().split()
        if len(tokens) == 0:
            raise ValueError("Cannot parse empty token stream.")

        parse_tree_1 = {
            "interpretation": "High-Probability Parse (Transactions executed last month)",
            "structure": (
                "[VP [VP Show me [NP transactions]] "
                "[PP with the card] [PP from last month]]"
            ),
            "meaning": "Fetch transactions made using the card where transaction_date = last_month.",
            "rule_probability": self.pcfg_rules["VP -> VP PP_card PP_time"]
        }

        parse_tree_2 = {
            "interpretation": "Low-Probability Parse (Card issued/created last month)",
            "structure": (
                "[VP Show me [NP transactions [PP with "
                "[NP the card [PP from last month]]]]]"
            ),
            "meaning": "Fetch transactions for a specific card that was acquired last month.",
            "rule_probability": self.pcfg_rules["NP -> NP PP_time"]
        }

        return {
            "query": query,
            "trees": [parse_tree_1, parse_tree_2],
            "best_parse": parse_tree_1 if parse_tree_1["rule_probability"] > parse_tree_2["rule_probability"] else parse_tree_2
        }

    @staticmethod
    def unify_feature_structures(fs1: Dict[str, Any], fs2: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Performs Feature Structure Unification for Subject-Verb Agreement.
        Returns unified feature dictionary if compatible, else None.
        """
        unified: Dict[str, Any] = {}
        all_keys = set(fs1.keys()).union(set(fs2.keys()))

        for key in all_keys:
            val1 = fs1.get(key)
            val2 = fs2.get(key)

            if val1 is not None and val2 is not None:
                if val1 == val2:
                    unified[key] = val1
                else:
                    # Agreement failure (e.g., Singular vs Plural)
                    return None
            elif val1 is not None:
                unified[key] = val1
            else:
                unified[key] = val2

        return unified


def run_demo_q1(user_query: Optional[str] = None) -> None:
    """Runs interactive and hardcoded demonstrations for Question 1."""
    parser = BankingQueryParser()

    query = user_query or "Show me the transactions with the card from last month"
    print("=" * 70)
    print("QUESTION 1: BANKING CHATBOT QUERY PARSER")
    print("=" * 70)

    # 1. Ambiguity Analysis & PCFG Evaluation
    try:
        result = parser.analyze_ambiguity(query)
        print(f"\n[Input Query]: '{result['query']}'\n")
        print("--- PARSE TREES GENERATED BY CFG/PCFG ---")
        for idx, tree in enumerate(result["trees"], 1):
            print(f"\nParse Tree #{idx}: {tree['interpretation']}")
            print(f"  Structure   : {tree['structure']}")
            print(f"  Semantics   : {tree['meaning']}")
            print(f"  PCFG Weight : {tree['rule_probability']}")

        print("\n--- PCFG AMBIGUITY RESOLUTION VERDICT ---")
        print(f"Selected Parse: {result['best_parse']['interpretation']}")
        print(f"Reasoning     : Higher PCFG weight ({result['best_parse']['rule_probability']}) prioritizes transaction-level temporal filtering.")

    except ValueError as err:
        print(f"[Error]: {err}")

    # 2. Subject-Verb Agreement Verification (Feature Structure Unification)
    print("\n--- FEATURE STRUCTURE AGREEMENT CHECK ---")
    
    # Valid Subject-Verb Pair
    subj_valid = {"CAT": "NP", "NUM": "sg", "PERS": 3}
    verb_valid = {"CAT": "VP", "NUM": "sg", "PERS": 3}
    res_valid = parser.unify_feature_structures(subj_valid, verb_valid)
    print(f"Valid Pair   ('The customer' + 'checks') -> Unified FS: {res_valid}")

    # Invalid Subject-Verb Pair
    subj_invalid = {"CAT": "NP", "NUM": "pl", "PERS": 3}
    verb_invalid = {"CAT": "VP", "NUM": "sg", "PERS": 3}
    res_invalid = parser.unify_feature_structures(subj_invalid, verb_invalid)
    print(f"Invalid Pair ('The customers' + 'checks') -> Unified FS: {res_invalid} (Agreement Error Blocked)")


if __name__ == "__main__":
    # Hardcoded test run
    run_demo_q1()
